apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stigatron-ui-cr
rules:
- apiGroups: ["management.cattle.io"]
  resources: ["settings"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stigatron-ui-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stigatron-ui-cr
subjects:
  - kind: ServiceAccount
    name: {{ include "stigatron-ui.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}