apiVersion: cis.cattle.io/v1
kind: ClusterScanBenchmark
metadata:
  name: rke2-stig-1.30-preview
  annotations:
    field.cattle.io/description: RKE2 1.30 STIG Profile
spec:
  clusterProvider: rke2
  customBenchmarkConfigMapName: rke2-stig-1.30-preview
  customBenchmarkConfigMapNamespace: cis-operator-system
  minKubernetesVersion: "1.30.0"
  maxKubernetesVersion: "1.30.30"