apiVersion: v1
kind: Service
metadata:
  name: heimdall-proxy
spec:
  type: {{ .Values.proxy.service.type }}
  selector:
    cattle.io/app: heimdall-proxy
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.proxy.service.port  }}
    targetPort: http