apiVersion: cis.cattle.io/v1
kind: ClusterScanBenchmark
metadata:
  name: rke2-stig-1.26
  annotations:
    field.cattle.io/description: RKE2 1.26 STIG Profile
spec:
  clusterProvider: rke2
  customBenchmarkConfigMapName: rke2-stig-1.26
  customBenchmarkConfigMapNamespace: cis-operator-system
  minKubernetesVersion: "1.26.0"
  maxKubernetesVersion: "1.26.30"