apiVersion: cis.cattle.io/v1
kind: ClusterScanBenchmark
metadata:
  name: rke2-stig-1.27
  annotations:
    field.cattle.io/description: RKE2 1.27 STIG Profile
spec:
  clusterProvider: rke2
  customBenchmarkConfigMapName: rke2-stig-1.27
  customBenchmarkConfigMapNamespace: cis-operator-system
  minKubernetesVersion: "1.27.0"
  maxKubernetesVersion: "1.27.30"